# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/mars/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),mars)

$(call add-radio-file-sha1-checked,radio/abl.img,a2c5fe0e92d9851f2fbb2a278342d310a932e176)
$(call add-radio-file-sha1-checked,radio/aop.img,63e19b53fb0127f76e9e2f8933b48d582a8d7c15)
$(call add-radio-file-sha1-checked,radio/bluetooth.img,1448ae8fdd59db2157437169521a993528e7854e)
$(call add-radio-file-sha1-checked,radio/cpucp.img,aba56751b001918e3bd42dd24b6b99148b469c0b)
$(call add-radio-file-sha1-checked,radio/devcfg.img,df0a55f5ee2bdc166a51a0d738a20e0ac4fd3c40)
$(call add-radio-file-sha1-checked,radio/dsp.img,1e07347b9a2ea338faeccf85c9be82d7be2d785a)
$(call add-radio-file-sha1-checked,radio/featenabler.img,ce35a16dcfe7a80535cb82cf5b71c5cc9a6f4ae9)
$(call add-radio-file-sha1-checked,radio/hyp.img,4438a70265c83d9b58461233eb1303517338565c)
$(call add-radio-file-sha1-checked,radio/imagefv.img,ea703e0284b265d85b62eec9a6bca144112ec09d)
$(call add-radio-file-sha1-checked,radio/keymaster.img,fd33f44e4d2b8733c65c73e2b2b03950f8563867)
$(call add-radio-file-sha1-checked,radio/modem.img,35cd1ef9b60bcb7f52c86b525a5d6165d9f2e53d)
$(call add-radio-file-sha1-checked,radio/qupfw.img,34ade23dc724ce771a65a117327d29aefc96a4d8)
$(call add-radio-file-sha1-checked,radio/shrm.img,95888038973765a0936d017c9f8109214582052a)
$(call add-radio-file-sha1-checked,radio/tz.img,17a600e9ea4d022d06e4bcf6fd079119a3f8e95d)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,4db2d288a8798d845187bdcf2a07b0d1cee08494)
$(call add-radio-file-sha1-checked,radio/xbl.img,43a6a6e42f8007b7cb792d3604cb92576f4e9430)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,a9f9a31b8ef12f651f4abcb8968b752de04e9a32)

endif
