# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/mars/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),mars)

$(call add-radio-file-sha1-checked,radio/abl.img,bba4365cb24e8a7e604a6cc3bbc31e6aadc3a462)
$(call add-radio-file-sha1-checked,radio/aop.img,0d24cc033a8bc41211c384c22ab0989deb73f0e0)
$(call add-radio-file-sha1-checked,radio/bluetooth.img,c2521002d4140a753a562e37d12edb3a197cb65e)
$(call add-radio-file-sha1-checked,radio/cpucp.img,24d511cf6de65bd5b6ecb3f15a4728edc1b0d0f5)
$(call add-radio-file-sha1-checked,radio/devcfg.img,3b4efb329a5e3e8286be046949e9385a19428b94)
$(call add-radio-file-sha1-checked,radio/dsp.img,8b27181b72bcc6cc003e5c21bac38993e7015995)
$(call add-radio-file-sha1-checked,radio/featenabler.img,b4f448f0504c426a4ec5d674d0f79c0e98a4f45b)
$(call add-radio-file-sha1-checked,radio/hyp.img,e57ea80e7a0acadc196e765f9555dbe9d4142175)
$(call add-radio-file-sha1-checked,radio/imagefv.img,b0be6bbce2e7e86cfada6e24ecce0ebb16c640f0)
$(call add-radio-file-sha1-checked,radio/keymaster.img,ffe0958d51fba31bd99f6116ae8f10cf0b6451dc)
$(call add-radio-file-sha1-checked,radio/modem.img,fe663cfe4bfbcdbf7f1f7d6846e54abd33aac4c9)
$(call add-radio-file-sha1-checked,radio/qupfw.img,3c6c13a996be6c55b90e070602fad8909e8277a5)
$(call add-radio-file-sha1-checked,radio/shrm.img,028fba17cf1a88ad8ee7b0bcec7f980a81995908)
$(call add-radio-file-sha1-checked,radio/tz.img,2591387a4392685a2bef127b77eb80a3ae851801)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,3cc706a0d4a6acc5bce4556f708c5118a780a0b6)
$(call add-radio-file-sha1-checked,radio/xbl.img,71d4ae03575922e69358ff0119324a2b709bcd26)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,300693e2e6f41e93e343a6c3f0d035ee7a153637)

endif
