# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/mars/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),mars)

$(call add-radio-file-sha1-checked,radio/abl.img,bb6398be1465e088fd50b736abce7b460b85827d)
$(call add-radio-file-sha1-checked,radio/aop.img,e36fa9e44801dfda48b1464b63713ed380233ce7)
$(call add-radio-file-sha1-checked,radio/bluetooth.img,56e3184b0a8ddeabe4145c5a2e155fbe7f3916b1)
$(call add-radio-file-sha1-checked,radio/cpucp.img,e8e8737e06bdc40c1c3f1254b87399304d355ffc)
$(call add-radio-file-sha1-checked,radio/devcfg.img,5cea48e74eb0fd6d0e24896e3c3b66c49b82bc28)
$(call add-radio-file-sha1-checked,radio/dsp.img,8b27181b72bcc6cc003e5c21bac38993e7015995)
$(call add-radio-file-sha1-checked,radio/featenabler.img,498801745ba598ee94c4dfec323d08f3e63f1e81)
$(call add-radio-file-sha1-checked,radio/hyp.img,d8bd553817d9217ebfbb036cf9c8978b35b793a5)
$(call add-radio-file-sha1-checked,radio/imagefv.img,84f7682cb7d89d47318506f1cd61b9762956092e)
$(call add-radio-file-sha1-checked,radio/keymaster.img,e28dfb89a6c8dc47bb1b8e381f2a21006c1208be)
$(call add-radio-file-sha1-checked,radio/modem.img,2e4b1124dd1bce1a06c3475a43faba930bc07ecc)
$(call add-radio-file-sha1-checked,radio/qupfw.img,6c8c72888af9e77d87c127157ac49be3e912f981)
$(call add-radio-file-sha1-checked,radio/shrm.img,b43d2d59cbe0a1a8b1338e0fc880c560dd1f30d5)
$(call add-radio-file-sha1-checked,radio/tz.img,95cf147f3af793eb8cbdcd53f043c3e9ba860796)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,cd680113bd9fdcdb1d8fd97aa5b8f05b298bcff5)
$(call add-radio-file-sha1-checked,radio/xbl.img,44cef5e8cd79bd0cd8edfbe3e7ad1c6f595f1c81)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,a1cc69a6ee2236d2ac013ea0dab2e7a5591a5845)

endif
